# Generated by Django 2.2.8 on 2021-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Vegetable'), (2, 'Fruits')], default=0),
        ),
    ]
